//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatUtils.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BatUtils.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAT Utils.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addr:Port.
        /// </summary>
        public static string ClientAddrAndPort {
            get {
                return ResourceManager.GetString("ClientAddrAndPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string ClientCheck {
            get {
                return ResourceManager.GetString("ClientCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore.
        /// </summary>
        public static string ClientExplore {
            get {
                return ResourceManager.GetString("ClientExplore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string ClientGeneral {
            get {
                return ResourceManager.GetString("ClientGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Info.
        /// </summary>
        public static string ClientInfo {
            get {
                return ResourceManager.GetString("ClientInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string ClientMore {
            get {
                return ResourceManager.GetString("ClientMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string ClientOpen {
            get {
                return ResourceManager.GetString("ClientOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RK7.
        /// </summary>
        public static string ClientRK7 {
            get {
                return ResourceManager.GetString("ClientRK7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ClientsAdd {
            get {
                return ResourceManager.GetString("ClientsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string ClientsCode {
            get {
                return ResourceManager.GetString("ClientsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ClientsDelete {
            get {
                return ResourceManager.GetString("ClientsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete client &quot;{0}&quot;?.
        /// </summary>
        public static string ClientsDeleteQuestion {
            get {
                return ResourceManager.GetString("ClientsDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete client.
        /// </summary>
        public static string ClientsDeleteTitle {
            get {
                return ResourceManager.GetString("ClientsDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ClientsEdit {
            get {
                return ResourceManager.GetString("ClientsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SH5.
        /// </summary>
        public static string ClientSH5 {
            get {
                return ResourceManager.GetString("ClientSH5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ClientsName {
            get {
                return ResourceManager.GetString("ClientsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string ClientsRefresh {
            get {
                return ResourceManager.GetString("ClientsRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ClientStatus {
            get {
                return ResourceManager.GetString("ClientStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Client.
        /// </summary>
        public static string ClientWindowAddTitle {
            get {
                return ResourceManager.GetString("ClientWindowAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string ClientWindowCode {
            get {
                return ResourceManager.GetString("ClientWindowCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Client.
        /// </summary>
        public static string ClientWindowEditTitle {
            get {
                return ResourceManager.GetString("ClientWindowEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid RK7 port.
        /// </summary>
        public static string ClientWindowInvalidRKPort {
            get {
                return ResourceManager.GetString("ClientWindowInvalidRKPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SH5 port.
        /// </summary>
        public static string ClientWindowInvalidSHPort {
            get {
                return ResourceManager.GetString("ClientWindowInvalidSHPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ClientWindowName {
            get {
                return ResourceManager.GetString("ClientWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RK Address.
        /// </summary>
        public static string ClientWindowRKAddress {
            get {
                return ResourceManager.GetString("ClientWindowRKAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RK Port.
        /// </summary>
        public static string ClientWindowRKPort {
            get {
                return ResourceManager.GetString("ClientWindowRKPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SH Address.
        /// </summary>
        public static string ClientWindowSHAddress {
            get {
                return ResourceManager.GetString("ClientWindowSHAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SH Port.
        /// </summary>
        public static string ClientWindowSHPort {
            get {
                return ResourceManager.GetString("ClientWindowSHPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code and name are required.
        /// </summary>
        public static string ClientWindowValidationCodeName {
            get {
                return ResourceManager.GetString("ClientWindowValidationCodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        public static string ClientWindowValidationTitle {
            get {
                return ResourceManager.GetString("ClientWindowValidationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string InfoTitle {
            get {
                return ResourceManager.GetString("InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string NavClients {
            get {
                return ResourceManager.GetString("NavClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string NavInfo {
            get {
                return ResourceManager.GetString("NavInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string NavSettings {
            get {
                return ResourceManager.GetString("NavSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string NavTools {
            get {
                return ResourceManager.GetString("NavTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string SettingsAppearance {
            get {
                return ResourceManager.GetString("SettingsAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingsLanguage {
            get {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string SettingsLanguageEnglish {
            get {
                return ResourceManager.GetString("SettingsLanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string SettingsLanguageRussian {
            get {
                return ResourceManager.GetString("SettingsLanguageRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string SettingsTheme {
            get {
                return ResourceManager.GetString("SettingsTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string SettingsThemeDark {
            get {
                return ResourceManager.GetString("SettingsThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string SettingsThemeLight {
            get {
                return ResourceManager.GetString("SettingsThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string ToolsTitle {
            get {
                return ResourceManager.GetString("ToolsTitle", resourceCulture);
            }
        }
    }
}
